apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-humio-repository-action-managed
spec:
  managedClusterName: example-humiocluster
  name: example-humio-repository-action
  viewName: humio
  humioRepositoryProperties:
    ingestToken: 
      secretKeyRef:
        name: humio-ingest-token
        key: token
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-humio-repository-action-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-humio-repository-action
  viewName: humio
  humioRepositoryProperties:
    ingestToken:
      secretKeyRef:
        name: humio-ingest-token
        key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: humio-ingest-token 
type: Opaque
data:
  token: c29tZS1odW1pby1pbmdlc3QtdG9rZW4K
