apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-slack-post-message-action-managed
spec:
  managedClusterName: example-humiocluster
  name: example-slack-post-message-action
  viewName: humio
  slackPostMessageProperties:
    apiToken:
      secretKeyRef:
        name: slack-api-token
        key: token
    channels:
      - "#some-channel"
      - "#some-other-channel"
    fields:
      query: "{query}"
      time-interval: "{query_time_interval}"
---
apiVersion: core.humio.com/v1alpha1
kind: HumioAction
metadata:
  name: humio-slack-post-message-action-external
spec:
  externalClusterName: example-humioexternalcluster
  name: example-slack-post-message-action
  viewName: humio
  slackPostMessageProperties:
    apiToken:
      secretKeyRef:
        name: slack-api-token
        key: token
    channels:
      - "#some-channel"
      - "#some-other-channel"
    fields:
      query: "{query}"
      time-interval: "{query_time_interval}"
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-api-token 
type: Opaque
data:
  token: c29tZS1mYWtlLXNsYWNrLXRva2Vu
